import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  architectsSidebar: [{type: 'autogenerated', dirName: 'architects'}],
  engineersSidebar: [{type: 'autogenerated', dirName: 'engineers'}],
  maintainersSidebar: [{type: 'autogenerated', dirName: 'maintainers'}],
  runbooksSidebar: [{type: 'autogenerated', dirName: 'runbooks'}],
  decisionsSidebar: [{type: 'autogenerated', dirName: 'decisions'}],
  implementationSidebar: [{type: 'autogenerated', dirName: 'implementation'}],
  preCodeSidebar: [{type: 'autogenerated', dirName: 'pre-code'}],
  generatedSidebar: [{type: 'autogenerated', dirName: 'generated'}],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
};

export default sidebars;