import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  usersSidebar: [{type: 'autogenerated', dirName: 'users'}],
  architectsSidebar: [{type: 'autogenerated', dirName: 'architects'}],
  engineersSidebar: [{type: 'autogenerated', dirName: 'engineers'}],
  maintainersSidebar: [{type: 'autogenerated', dirName: 'maintainers'}],
  tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  glossarySidebar: [{type: 'autogenerated', dirName: 'glossary'}],
};

export default sidebars;